### ISSUE TITLE
Cannot submit pull request due to missing .env file

### ISSUE THREAD

**Issue by hannaholiero** [Netflix-Fab-5/NetflixBackend#27]
I am unable to submit my pull request because the project requires the .env file, which is not currently shared. This is causing ESLint to fail during the checks.

To ensure that ESLint passes, we need access to the necessary environment variables specified in the .env file.

Please share the documentation (jamen någonstans säkert, typ i gruppen internt).
Thank you!

**Comment by ulle73** [comment]
file uploaded on discord @hannaholiero
